### ISSUE TITLE
After setting up LiveTestConfiguration.json, errors regarding authentication

### ISSUE THREAD

**Issue by DonSchenck** [openstacknetsdk/openstack.net#498]
The `authenticationRequest` is null, which see.

It appears as though there's no authentication taking place during some tests.

```
Test Name:	TestListServices
Test FullName:	OpenStackNetTests.Live.ContentDeliveryTests.TestListServices
Test Source:	c:\Users\Administrator\Documents\Visual Studio 2013\Projects\openstack.net\src\OpenStackNetTests.Live\ContentDeliveryTests.Shared.cs : line 266
Test Outcome:	Failed
Test Duration:	0:00:00.0059727

Result Message:	
Test method OpenStackNetTests.Live.ContentDeliveryTests.TestListServices threw exception: 
System.ArgumentNullException: Value cannot be null.
Parameter name: authenticationRequest
Result StackTrace:	
at OpenStack.Security.Authentication.IdentityV2AuthenticationService..ctor(IIdentityService identityService, AuthenticationRequest authenticationRequest) in c:\Users\Administrator\Documents\Visual Studio 2013\Projects\openstack.net\src\OpenStack.Net\OpenStack\Security\Authentication\IdentityV2AuthenticationService.cs:line 59
   at Rackspace.Security.Authentication.RackspaceAuthenticationService..ctor(IIdentityService identityService, AuthenticationRequest authenticationRequest) in c:\Users\Administrator\Documents\Visual Studio 2013\Projects\openstack.net\src\OpenStack.Net\Rackspace\Security\Authentication\RackspaceAuthenticationService.cs:line 34
   at OpenStackNetTests.Live.IdentityV2Tests.CreateAuthenticationService(TestCredentials credentials, Boolean logRequests) in c:\Users\Administrator\Documents\Visual Studio 2013\Projects\openstack.net\src\OpenStackNetTests.Live\IdentityV2Tests.Shared.cs:line 425
   at OpenStackNetTests.Live.ContentDeliveryTests.CreateService() in c:\Users\Administrator\Documents\Visual Studio 2013\Projects\openstack.net\src\OpenStackNetTests.Live\ContentDeliveryTests.Shared.cs:line 480
   at OpenStackNetTests.Live.ContentDeliveryTests.<TestListServices>d__68.MoveNext() in c:\Users\Administrator\Documents\Visual Studio 2013\Projects\openstack.net\src\OpenStackNetTests.Live\ContentDeliveryTests.Shared.cs:line 272
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
```

**Comment by sharwell** [comment]
I marked this as a bug. The authentication request selection code should detect the configuration error (or inconsistency) that lead to this, and report it earlier and with a more appropriate message.

**Comment by carolynvs** [comment]
Closing v2 bugs
