### ISSUE TITLE
Chunked encoding upload is not supported on the HTTP/1.0 protocol (AGAIN)

### ISSUE THREAD

**Issue by tommymonk** [openstacknetsdk/openstack.net#643]
We appear to be experiencing the  exact same effects as resolved by issue [333](https://github.com/openstacknetsdk/openstack.net/issues/333)

A Windows service pushing objects into cloud files suddenly experiences many of the following exception and continues in this broken state until restarted

We're using openstack.net v1.7.7 and rackspace v0.2.0, the Windows service is running .NET 4.6.2 on Windows Server 2012 R2

<pre>System.Net.ProtocolViolationException: Chunked encoding upload is not supported on the HTTP/1.0 protocol.
   at System.Net.HttpWebRequest.CheckProtocol(Boolean onRequestStream)
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at net.openstack.Providers.Rackspace.ExtendedJsonRestServices.<>c__DisplayClass0_0.<Stream>b__0(HttpWebRequest req) in C:\Bamboo\xml-data\build-dir\OSTK-NET19-BLD\src\corelib\Providers\Rackspace\ExtendedJsonRestServices.cs:line 49
   at JSIStudios.SimpleRESTServices.Client.RestServiceBase.<>c__DisplayClass23_0.<ExecuteRequest>b__0() in Y:\src\SimpleRestServices\src\SimpleRestServices\Client\RestServiceBase.cs:line 450
   at JSIStudios.SimpleRESTServices.Client.RequestRetryLogic.Execute(Func`1 callback, IEnumerable`1 non200SuccessCodes, Int32 retryCount, Nullable`1 retryDelay) in Y:\src\SimpleRestServices\src\SimpleRestServices\Client\WebResponseRetryLogic.cs:line 56
   at JSIStudios.SimpleRESTServices.Client.RestServiceBase.ExecuteRequest(Uri url, HttpMethod method, Func`3 responseBuilderCallback, Dictionary`2 headers, Dictionary`2 queryStringParameters, RequestSettings settings, Func`2 executeCallback) in Y:\src\SimpleRestServices\src\SimpleRestServices\Client\RestServiceBase.cs:line 408
   at net.openstack.Providers.Rackspace.ExtendedJsonRestServices.Stream(Uri url, HttpMethod method, Func`3 responseBuilderCallback, Stream content, Int32 bufferSize, Int64 maxReadLength, Dictionary`2 headers, Dictionary`2 queryStringParameters, RequestSettings settings, Action`1 progressUpdated) in C:\Bamboo\xml-data\build-dir\OSTK-NET19-BLD\src\corelib\Providers\Rackspace\ExtendedJsonRestServices.cs:line 38
   at JSIStudios.SimpleRESTServices.Client.RestServiceBase.Stream(Uri url, HttpMethod method, Stream content, Int32 bufferSize, Int64 maxReadLength, Dictionary`2 headers, Dictionary`2 queryStringParameters, RequestSettings settings, Action`1 progressUpdated) in Y:\src\SimpleRestServices\src\SimpleRestServices\Client\RestServiceBase.cs:line 254
   at net.openstack.Providers.Rackspace.ProviderBase`1.StreamRESTRequest(CloudIdentity identity, Uri absoluteUri, HttpMethod method, Stream stream, Int32 chunkSize, Int64 maxReadLength, Dictionary`2 queryStringParameter, Dictionary`2 headers, Boolean isRetry, RequestSettings requestSettings, Action`1 progressUpdated) in C:\Bamboo\xml-data\build-dir\OSTK-NET19-BLD\src\corelib\Providers\Rackspace\ProviderBase`1.cs:line 623
   at net.openstack.Providers.Rackspace.CloudFilesProvider.CreateObject(String container, Stream stream, String objectName, String contentType, Int32 chunkSize, Dictionary`2 headers, String region, Action`1 progressUpdated, Boolean useInternalUrl, CloudIdentity identity) in C:\Bamboo\xml-data\build-dir\OSTK-NET19-BLD\src\corelib\Providers\Rackspace\CloudFilesProvider.cs:line 1035<pre>

**Comment by ndphuong** [comment]
I have this problem too.
It gone when I restart service

**Comment by ndphuong** [comment]
It still happen again. Don't have anyone can fix it ?

**Comment by tommymonk** [comment]
This driver should probably be considered abandoned especially for anyone using with Rackspace.

The previous maintainer worked for Rackspace which made sense as they had a vested interest for their cloud platform sdk.

Rackspace have now communicated to clients that they're freezing product development and effectively end-of-life their cloud platform.
They're persuading customers over to AWS in the hope that they retain them for support.

This is causing us pain with regard to #650

**Comment by ndphuong** [comment]
@tommymonk 
Your mean is we should find another SDK ?
We are using OVH Object Storage (https://www.ovh.com/us/public-cloud/storage/object-storage/), not sure relate to Rackspace

**Comment by tommymonk** [comment]
At the moment this SDK is between maintainers, unless someone steps up it will remain in this state.

We've contacted Rackspace to find if/when someone else from their dev team would take over from Carolyn (who no longer works for them) but were told it's unlikely due to the aforementioned road-map changes they're making following their acquisition by Apollo Global Management.

Unlike yourself, we don't have the luxury of choosing a different openstack driver as the [Rackspace](https://www.nuget.org/packages/Rackspace) driver depends on this one, and was also maintained by Carolyn.

**Comment by HayS33d** [comment]
I have pulled the source code and updated the Flurl and Flurl.Http version. If anyone is still using this...

**Comment by sridharpettela** [comment]
> 
> 
> I have pulled the source code and updated the Flurl and Flurl.Http version. If anyone is still using this...

is this resolved the issue?
